// Hardcoded care info. Eventually this could be a queryable table, but for v1
// it's a static lookup with substring fallback.

const CARE_DB = {
  'squash':{sun:'Full sun',water:'Deep water 1–2x/week; keep soil consistently moist.',soil:'Rich, well-draining soil with compost; pH 6.0–6.8.',spacing:'24–36 inches apart',harvest:'50–65 days; harvest summer squash at 6–8 inches.',fertilizer:'Balanced fertilizer at planting, low-nitrogen once flowering.',pests:['Squash vine borers','Squash bugs','Cucumber beetles'],tips:['In Texas heat, shade cloth in July–August prevents blossom drop.','Mulch heavily to retain moisture.','Plant a second round in late July for fall harvest.']},
  'cantaloupe':{sun:'Full sun',water:'1–2 inches/week; reduce as fruit ripens for sweeter flavor.',soil:'Sandy loam, well-draining; pH 6.0–6.8.',spacing:'36 inches apart; allow vines to trail.',harvest:'75–90 days; ripe when stem slips easily.',fertilizer:'High nitrogen early, switch to P/K at flowering.',pests:['Aphids','Cucumber beetles','Powdery mildew'],tips:['Texas summers are ideal — plant after last frost.','Place fruit on a board to keep off hot soil.','Stop watering 1 week before harvest.']},
  'bell pepper':{sun:'Full sun (6–8 hrs min)',water:'1–2 inches/week; consistent moisture prevents blossom end rot.',soil:'Well-draining, fertile soil; pH 6.0–6.8.',spacing:'18–24 inches apart',harvest:'60–90 days; green at maturity, longer for color.',fertilizer:'Low N at planting, more P/K at first bloom.',pests:['Aphids','Pepper weevils','Spider mites'],tips:['Texas summers above 95°F can cause blossom drop — shade cloth helps.','Mulch 3–4 inches deep.','Stake plants early; loaded branches snap in storms.']},
  'jalapeño':{sun:'Full sun',water:'1 inch/week; slight drought stress increases heat.',soil:'Well-draining, fertile; pH 6.0–6.8.',spacing:'14–18 inches apart',harvest:'70–85 days; harvest green or red.',fertilizer:'Balanced at transplant; limit N mid-season.',pests:['Aphids','Pepper maggots','Bacterial leaf spot'],tips:['Thrives in Texas heat — one of the best peppers for zone 7b/8a.','Stress slightly before harvest for hotter peppers.','Can overwinter indoors in a pot.']},
  'serrano':{sun:'Full sun',water:'1 inch/week; tolerates heat well.',soil:'Well-draining, fertile; pH 6.0–6.8.',spacing:'18–24 inches apart',harvest:'75–90 days; harvest green or red.',fertilizer:'Light feeding; avoid over-N.',pests:['Aphids','Spider mites','Flea beetles'],tips:['More heat-tolerant than jalapeño.','Higher capsaicin; harvest smaller for more heat.','Prolific producer — 50+ peppers per plant.']},
  'thyme':{sun:'Full sun to partial shade',water:'Low water; drought-tolerant once established.',soil:'Well-draining, sandy or loamy; pH 6.0–8.0.',spacing:'12–18 inches apart',harvest:'Harvest sprigs anytime; trim before flowering.',fertilizer:'Light feeder; one balanced dose in spring.',pests:['Aphids (rare)','Spider mites in dry conditions'],tips:['Thrives in Texas heat — very low maintenance.','Trim after flowering to prevent woodiness.','Mulch lightly in winter for occasional hard freezes.']},
  'marigold':{sun:'Full sun',water:'Moderate; water at base; drought-tolerant once established.',soil:'Average, well-draining; pH 6.0–7.0.',spacing:'8–12 inches apart',harvest:null,fertilizer:'Light feeder; too much fertilizer = more foliage, fewer flowers.',pests:['Spider mites (in heat)','Slugs'],tips:['Repels aphids, nematodes, whiteflies — excellent companion plant.','Deadhead spent blooms for continuous flowering.','Texas heat may cause summer slow-down; rebounds in fall.']},
  'tomato':{sun:'Full sun',water:'1–2 inches/week, deep watering at base.',soil:'Rich, well-draining, slightly acidic; pH 6.2–6.8.',spacing:'24–36 inches apart',harvest:'60–85 days depending on variety.',fertilizer:'Balanced at planting; switch to lower N at flowering.',pests:['Hornworms','Whiteflies','Blossom end rot (calcium issue)'],tips:['Texas heat can halt fruit set above 95°F — shade cloth helps.','Stake or cage early.','Mulch heavily to maintain even moisture.']},
  'basil':{sun:'Full sun',water:'Keep soil consistently moist but not soggy.',soil:'Rich, well-draining; pH 6.0–7.0.',spacing:'12–18 inches apart',harvest:'Pinch leaves continuously; cut flowers to extend production.',fertilizer:'Light feeder; balanced fertilizer monthly.',pests:['Aphids','Japanese beetles','Downy mildew'],tips:['Pinch flowers immediately to prolong leaf production.','Loves Texas heat as long as it has water.','Companion plants well with tomatoes.']},
  'rosemary':{sun:'Full sun',water:'Drought-tolerant; let soil dry between waterings.',soil:'Well-draining, slightly alkaline; pH 6.0–7.5.',spacing:'24–36 inches apart',harvest:'Cut sprigs anytime; never more than 1/3 at once.',fertilizer:'Minimal feeding; light spring fertilizer.',pests:['Spider mites','Powdery mildew'],tips:['Excellent for Texas — very drought-tolerant.','Avoid overwatering; root rot is the biggest risk.','Can grow into a small shrub over years.']},
  'lavender':{sun:'Full sun',water:'Drought-tolerant; water deeply but infrequently.',soil:'Well-draining, sandy, slightly alkaline; pH 6.7–7.3.',spacing:'18–36 inches apart',harvest:'Harvest flowers when buds open; cut stems long.',fertilizer:'Minimal; lavender prefers lean soil.',pests:['Spittlebugs','Root rot from overwatering'],tips:['Texas summers: French/Spanish lavender handles heat better than English.','Excellent drainage is critical.','Prune after flowering to shape and prevent woodiness.']},
};

export function getCare(label) {
  if (!label) return null;
  const k = label.toLowerCase();
  if (CARE_DB[k]) return CARE_DB[k];
  for (const key of Object.keys(CARE_DB)) {
    if (k.includes(key) || key.includes(k.split(/[\s(]/)[0])) return CARE_DB[key];
  }
  return null;
}
